name: Generate ASCII Artwork Step by Step

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute Cowsay
        run: cowsay -f dragon "Run for cover, I am a DRAGON... RAWR" > dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
            name: dragon-text-file
            path: dragon.txt
        

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file        

      - name: Test file contains dragon
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: [test_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file 

      - name: Read file
        run: cat dragon.txt
