# name: Exploring Variables and Secrets

#
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         run: docker build -t docker.io/dockerUsername/imageName:latest .
#
#       - name: Docker Login
#         run: docker login --username dockerUsername --password s3cUrePaSsw0rd
#
#       - name: Docker Publish
#         run: docker push docker.io/dockerUsername/imageName:latest
#
#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Run
#         run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
#
#
# ### environment variables at STEP level #####
#
# name: Exploring Variables and Secrets
#

#
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: siddharth1
#           IMAGE_NAME: github-actions-nginx
#         run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .
#
#       - name: Docker Login
#         env:
#           DOCKER_USERNAME: siddharth1
#           DOCKER_PASSWORD: s3cUrePaSsw0rd
#         run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#
#       - name: Docker Publish
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: siddharth1
#           IMAGE_NAME: github-actions-nginx
#         run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
#
#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Run
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: siddharth1
#           IMAGE_NAME: github-actions-nginx
#         run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
#
#
# ### environment variables at JOB level #####
#
# name: Exploring Variables and Secrets
#
# jobs:
#   docker:
#     env:
#       CONTAINER_REGISTRY: docker.io
#       DOCKER_USERNAME: siddharth1
#       IMAGE_NAME: github-actions-nginx
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .
#
#       - name: Docker Login
#         env:
#           DOCKER_PASSWORD: s3cUrePaSsw0rd
#         run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#
#       - name: Docker Publish
#         run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
#
#   deploy:
#     env:
#       CONTAINER_REGISTRY: docker.io
#       DOCKER_USERNAME: siddharth1
#       IMAGE_NAME: github-actions-nginx
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Run
#         run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
